# Generated by Django 2.2.7 on 2019-11-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_craigs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
